### ISSUE TITLE
Sobre workflow con Git

### ISSUE THREAD

**Issue by Mallku2** [MaicoLeberle/COMPIcompiler#2]
@crscardellino Podrías pasarme aquel documento que describía el modo en el que trabajás con Git?. Antes de ponerme a subir cosas...así no me la mando desde el comienzo =D.

**Comment by crscardellino** [comment]
@Mallku2 Puse en la wiki algunos links de interés:

https://github.com/MaicoLeberle/COMPIcompiler/wiki
