### ISSUE TITLE
node_expr hereda de node_statement?

### ISSUE THREAD

**Issue by Mallku2** [MaicoLeberle/COMPIcompiler#6]
@crscardellino @MaicoLeberle Pregunta: por qué node_expr hereda de node_statement?. No recuerdo a qué se debía eso, y ahora tengo problemas para compilar nuestro compilador, porque me exige re-definir el método type_of_statement, en toda clase que hereda de node_expr, ya que tal método ahora está como virtual puro.

**Comment by crscardellino** [comment]
No recuerdo bien porqué lo había hecho, pero tenía que ver con que si no heredaba de ahi el parser no lo podía terminar de parsear correctamente (bison me refiero), así que tuve que terminar haciendo que heredara. Si querés intentá sacarselo, pero estoy seguro de que va a joder con Bison.

**Comment by Mallku2** [comment]
@MaicoLeberle Efectivamente, como vos @crscardellino  decías, se me queja el parser, porque requiere que node_method_call "sea" un node_statement, cuando una llamada a método aparece como sentencia. Sería posible hacer que node_expr no herede de node_statement, y definir una clase que represente a un "method call" cuando es usado como expresión (y que, por lo tanto, herede sólo de node_expr) y otra clase que represente a un "method call", cuando es usado como sentencia (y, por lo tanto, hereda de node_statement)?. Ambas clases tendrían la misma información, sólo las haríamos para resolver este problema de tipos. Por cierto, no quiero meter mano en node.h, porque no sé si alguien ya lo está toqueteando.

**Comment by crscardellino** [comment]
@Mallku2 No sabría que decirte de eso al respecto. Si se pueden diferenciar bien los casos entonces no hay problema. Pero ni idea. Si querés meter mano en node.h sos libre de hacerlo por mi parte, yo no lo he tocado y lo último que hice lo subí todo.

**Comment by Mallku2** [comment]
@crscardellino Dale, meto mano en eso. También voy a tener que tocar algo de parser.y. Si no me equivoco, no haría falta tocar en otros lugares.
